### ISSUE TITLE
survey tools error: from photutils.background import Background

### ISSUE THREAD

**Issue by HBarker13** [barentsen/surveytools#8]
Hi, 
I installed surveytools using pip and I got an error from catalogue.py. I'm not using this script, just wanted to let you know:

Traceback (most recent call last):
  File "/home/hbarker/scripts/footprint.py", line 3, in <module>
    import surveytools
  File "/mirror/scratch/hbarker/pkgs/anaconda/lib/python2.7/site-packages/surveytools/__init__.py", line 39, in <module>
    from .catalogue import VphasFrame, VphasOffsetCatalogue
  File "/mirror/scratch/hbarker/pkgs/anaconda/lib/python2.7/site-packages/surveytools/catalogue.py", line 65, in <module>
    from photutils.background import Background
ImportError: cannot import name Background

I had a look a the documentation, and it looks like Background doesn't exists: http://photutils.readthedocs.io/en/stable/photutils/background.html

**Comment by barentsen** [comment]
Thanks for getting in touch!

Indeed, `surveytools` used an early version of `photutils`, including some functions which are now deprecated.  This package was only used once, three years ago, to create a source catalog for the VPHAS survey.  I am no longer maintaining this package and so I do not intend to fix this, but I appreciate you opening the issue! :+1:
